### ISSUE TITLE
using variables, setting and getting, on nodes like content or dialog nodes

### ISSUE THREAD

**Issue by whwptb** [mhgolkar/Arrow#11]
There are so many use cases where the variables need to be accessed on the script/story

ie

if a character's name could be set and get 

"hey XXX! We heard you are leaving the town"

or numbers and other strings

"yes. I am leaving within YY days to go to AA town and try to find BB and help out for CC"

its a simple problem that most users would probably be thankful for. instead of using multiple nodes that would eventually turn into spaghetti, why not just expose the variables on the nodes themeselves.

other similar tools has this functionality, and the said feature is the only reason i can't fully commit on using arrow

i really like your stand about JSON exports as its more versatile than what other tools are using.

thankyou in advance.
and youre doing a really good job.

**Comment by mhgolkar** [comment]
Hi @whwptb 

Thanks for using Arrow.

This feature already exists.
We just need to *place our variable name inside curly brackets*.
So your content or dialog line should be like this:

```
Hey {HERO_NAME}! We heard you are leaving the town.
```

The console will replace it with the *current value* of the variable `HERO_NAME` when the node is being played.
We can get a variable's current value in content-oriented node-types such as `Dialog` (lines), `Content` (title & text), `Interaction` and `User_Input` (prompt.)

Make sure to *use the latest Arrow*. It has received many updates recently.

Variable parsing existed since the first release of Arrow (editor,) but in the versions prior to v1.0.1 of the official HTML-JS runtime (used to export playable files,) this feature was missed from some important node-types.
Thanks to your issue, the runtime is fixed now.

I'll update Arrow's wiki on the Variables as soon as possible.
