### ISSUE TITLE
PathDialog Access property causes current_path and current_dir inconsistencies

### ISSUE THREAD

**Issue by MatteoPiovanelli-Laser** [mhgolkar/Arrow#15]
I am playing around with the project to learn stuff about it and about Godot.
I started by forking the repo, cloned it locally, opened it for edit in Godot 3.2.3.

Then I hit Play to start the project and played around with things a bit.
Importantly (for this issue) I set a different "Work Directory" from Arrow -> Preferences.

From git I noticed there were changes to main.tscn. The values of the properties of BlockingLayer.Container.PathDialog is now set to my custom value there.
Even after I went and reset it back to 'user://' from both the in-app preferences and directly in the Editor by changing the properties of PathDialog, the values in main.tscn remain to my "custom" values.

To push my changes "clean" of that, I have to edit main.tscn outside the Godot Editor. Then one I open it again and save any change, I'm back with my "custom" values.
Note that I tried reset my local code to what is here on the remote, to no avail: as soon as I start editing from the Godot Editor those values change again to my "custom" paths.

Am I doing something wrong somewhere? I guess I am missing something obvious that Godot is doing behind the scenes.

**Comment by MatteoPiovanelli-Laser** [comment]
I tried deleting everything related to Arrow from the userdata forlder where Godot puts its stuff. Then I delete the project from the hard drive entirely. Then I cloned it back. When I opened it those properties where again not "user://".

Later (when away from the computer) I realized that the path I see in the editor (and that is being "saved" in the tscn file) is the path on my d: drive where the project is.
I will look at this more when I get back to that computer.

**Comment by MatteoPiovanelli-Laser** [comment]
I actually think this may be the same as this Godot Issue: 
https://github.com/godotengine/godot/issues/29674

**Comment by MatteoPiovanelli-Laser** [comment]
I just checked.
Basically what I am seeing is caused by this:
![image](https://user-images.githubusercontent.com/19283945/113346165-ca34b880-9333-11eb-9368-fb963e49c54a.png)
That value of the `Access` property causes `current_dir` and `current_path` to change to the folder where the project is on my hard drive. If I set `Access = User data` in the Editor then those paths can be made to revert back to `user://` and keep that value.

There seems to also be something else at play, because sometimes when I ran the project I saw those values change from `user://` to `user://my/project/path`. But I can't reliably reproduce this right now.

I'll change the title of this issue to reflect the fact that the root of it seems to be that `Access` property.

**Comment by mhgolkar** [comment]
Hi

Godot updates some files automatically when you save a project for technical reasons.
Some of them never show up in diffs because the contents stay identical but the modification times get refreshed so in case you have a backup software sensitive to m-time, it may detect them as edited too.
In the case of  `PathDialog`, Godot currently keeps the paths in the scene files (as mentioned in the open godotengine/godot#29674.)

Technically the `Access` we want is `File System`, but yes, changing it to `User Data` will *workaround* the VCS inconsistencies in a level.
The reason this workaround works is because every time you open the `PathDialog` in runtime, Arrow *resets* the access property to `FileDialog.ACCESS_FILESYSTEM` otherwise by changing this property users wouldn't have access to any directory other than `user://*`. Thankfully Godot lets us resetting the property in runtime.

Though it's not the ultimate fix, I'll apply the workaround to make things easier for VCS.
> Better fix would be creating the whole `PathDialog` node in runtime, but it's not going to be a priority at all.

Thanks a lot @MatteoPiovanelli-Laser
