### ISSUE TITLE
Enhancement: Optionally reset/unset key after checking the value in `Tag Pass`

### ISSUE THREAD

**Issue by MJacred** [mhgolkar/Arrow#47]
This concept might need more refinement, but I have the following use case (this setup will repeat itself countless times),  
where the player should be able to branch off somewhere, but they must have handled, in some way or another, a specific topic. If it failed, they may need to repeat some part.  
And after each `Tag Pass` for said Character-tag-key, I want to reset the key, i.e. integrate purpose of Node `1y` into `Tag Pass`. (I know that in case of `1w` being `False`, it is not reset in the image below).

![image](https://user-images.githubusercontent.com/6639237/235371137-e5a0d8d3-bfab-4529-ada3-07b648335d07.png)

So something like this:

![image](https://user-images.githubusercontent.com/6639237/235372131-1e5c4d56-54ab-4d99-872b-f751de1042ec.png)

**Comment by mhgolkar** [comment]
Although it's quite easy to implement, there are few matters to be considered.
It will somehow break the unwritten rule for Arrow's built-in nodes to be atomic. It is also a breaking change internally, because we have to keep a new value in the node's dataset, specially affecting users serializing the node in their own custom ways.
The other point is that I recommend developers to use tags as unique gates and keep them in memory, unless they are sure they would not check for them anymore, specially if they are having a lot of them. Tags are designed mainly for dynamic (global) event management and are not that resource intensive. For example, I would consider setting `hero_revived` as a global state (with or without a value to know revival quality as a zombie, a promoted mage, etc.) to be  a safer practice compared to `revived = hero | cookie_monster | john_smith`.
Finally we can not really propose a one-size-fits-all solution: An unset always on false, always on true, on author's choice, a reset to the initial value (if initialized in the editor) or a reset to blank, ... which one is the proper convention?
These are some of the reasons why I prefer to keep things atomic and encourage users to create their own composite/custom nodes and even better to make them open-source.

Let's now close this issue; but I'm open to more discussion.

**Comment by MJacred** [comment]
> we can not really propose a one-size-fits-all solution


Hm… indeed

Then either add a `Tag Edit`-like logic beneath `Tag Pass` or create a new `Tag Pass Edit` node, where beneath the existing `Tag Pass` GUI, you can add/remove lines (maybe use Godot's `Tree`) such as

| Key | Operation | Value | On |
| -------- | ------- | ------- | ------- |
| cookie | Unset |  | Pass |
| health | To Initial |  | Fail |
| ice_cream_flavour | Set | Lemon | Fail |


`Operation` would be an OptionButton and `On` can be CheckButton

**Comment by mhgolkar** [comment]
That is probably the way to go if we wanted to create highly composite nodes built-in.
But the way I see it, from UX point of view, we are just replacing some slot connections with inspector fields that we will have to somehow display on the grid too. In other words, it is a matter of taste. Some developers may prefer more connections on the grid, some may prefer fields and bullet-points printed on the grid.
