### ISSUE TITLE
Feature: Node that displays an image

### ISSUE THREAD

**Issue by frigvid** [mhgolkar/Arrow#52]
While text-based games are primarily, well, text-based. It's not the first time I've seen one implement something of that kind using [SugarCube2](https://www.motoslave.net/sugarcube/2/), and I think it'd be nice to have the option to display images on the export along with text. It'd have to be a node that can be used together with other nodes, e.g. that is connected to a Content node, and displays the image along with the text. This may be a big change, as I presume you would have to add an image input on relevant nodes, but I think it'd still be really neat to have.

**Comment by mhgolkar** [comment]
Hi @frigvid 

Generally speaking, I try to avoid putting any feature in Arrow that I feel is highly game-play or runtime -specific.
It is part of the minimal (and quite opinionated) approach that I've chosen for this project.
Arrow is a narrative design tool first. Even the ability to create text-adventures with it, comes second.
In other words, Arrow's main goal is to help with creating DB or raw content files for your game or interactive document.

In that sense, displaying images is a very game-play/runtime -specific task.  
Our [official HTML-JS runtime] supports displaying images through *BBCode* (e.g. `[img]path/to/scene.png[/img]`) where ever it is available, including in the Content nodes. It is though very basic, because that is a minimal runtime intended mostly for debug and sharing purposes. And, at least for the time being, I do not plan to extended features of our official runtime beyond this.

In Arrow's terminology, projects like [SugarCube2](https://www.motoslave.net/sugarcube/2/) belong to the custom/extended (third-party) runtime projects category.
They are very welcome, and I'd be happy to promote the decent ones in Arrow's repository; but as far as I know, we do not have any yet! I hope we'll have more options in the near future.

Wish you best

[official HTML-JS runtime]: https://github.com/mhgolkar/Arrow/blob/main/runtimes/html-js
