### ISSUE TITLE
Enhancement: Allow usage of variables in Interactible node Actions

### ISSUE THREAD

**Issue by frigvid** [mhgolkar/Arrow#59]
Currently, as far as I'm aware, the usage of a variable in an Action means you just get the text of the variable and not of the value. E.g. I have a variable named `test_var` with a value of "variable" and use that in the Action like so `This is an Action with a {test_var}`, the output becomes the literal string and not the value of the string like `This is an Action with a variable`. I think this would be valuable to implement, as one may add names of people in a story to it when designing a story. It's a tad more necessary due to Characters not being allowed to have spaces in their names too, I think.

**Comment by mhgolkar** [comment]
If I'm getting your issue right, we are talking about [Variable Exposure] and similar behavior with [Character Tags].

I can not see any problem regarding any of these features.

If you mean getting variable names in the nodes on the grid: that behavior is intentional.
Nodes always show the name of variables (in placeholder form e.g. `{var_x}`) to make them easily distinguishable from normal text. They are expected to be *exposed/parsed as their values **in runtime** or console*.

![image](https://github.com/mhgolkar/Arrow/assets/1233337/9356c661-de46-4a0f-91b3-d01dd9865194)

In the demonstration above, `monster` is a string variable with value of `Gigantic Worm`,
and a character `Enemy` exists which has a tag named `name` with value `Mr. X`.

Also note that tag values can have white spaces, only names should avoid them.

[Variable Exposure]: https://github.com/mhgolkar/Arrow/wiki/variables-and-logic#variable-exposure-parsing
[Character Tags]: https://github.com/mhgolkar/Arrow/wiki/Characters#tags

**Comment by frigvid** [comment]
Hmm, stranger still then. I have seen variables that have been perfectly written (by copy and pasting it) still not be properly parsed when exported. It's been a while now, and I've been busy. I cannot remember if this was the case in-editor or not. But fair enough.

**Comment by mhgolkar** [comment]
In current state, things seem to be working fine.
We may be missing a corner case or special situation though, so if you experienced it again, please try to isolate the problem and create a reproduction project so we can hunt the cause.
