### ISSUE TITLE
Feature request: option to auto-update also when clicking on the same node

### ISSUE THREAD

**Issue by diegopau** [mhgolkar/Arrow#66]
Hi,

First of all a big thank you for sharing this wonderful piece of software with the world. I am still exploring its possibilities but it is a really powerful tool.

I struggle a bit to get used to click the Update button to prevent content deletion. I actually prefer to leave the Auto Node Update on and forget about clicking the Update button. I think there is a tendency with software in productivity software in general to assume that whatever you type is auto saved. For instance I used Scrivener a lot in the past and even if you can manually save, you just don't ever have to do it since by default it autosaves constantly. I don't care too much about the Project not being autosaved in Arrow since it will anyways remind you to save when you try to close the app.

In Arrow, with "Auto Node Update" on, I tend to forget about the need to click Update (and maybe the idea is that the need is not there anymore). However, I might be in the middle of writing some content and then go ahead and decide to adjust the node position, size, etc. without clicking Update.  This can happen for many reasons, like me being absent-minded, or coming back from taking a call and then my brain picking up that the position of the node is not ideal, etc. There is no warning about content not saved or anything, the changes just go away. An option (for absent-minded people like me) to change this behavior would be convenient.

What do you think of this?

EDIT: now that I remember a similar  thing that happens often to me is that I hit CTRL+Z to undo maybe the last word I input in the Content (this is just muscle memory from every other software where you type) and instead of undoing the last word or sentence, it will close the Node and discard all the changes. This was painful more than once... now I am more careful.

**Comment by mhgolkar** [comment]
Hi @diegopau 
Thanks for your kind words

I understand (re-phrase) the issue this way:
With *Auto Node Update* (quick preference) enabled, nodes are always updated when left, unless they are re-selected (i.e. being left and re-inspected, so resetting the parameters), which can be a headache when you forget such behavior exists and accidentally discard your changes.

There would be two strategies in my understanding to help with that:
1. to always update even in case of a re-selection (i.e. to softly leaving a node cause an update too) and let people reset parameters using other means when they want to,
2. add another preference to opt out of the automatic reset on re-inspection behavior, to avoid accidentally discarding the changes when touching a node again

I preferred to go with the second option, because it won't break current (probably familiarized) behavior, and
you would eventually leave and auto-update the node, which makes opting out of rest-on-reinspection almost the same as saving anyway.

The commit [1f9e838](https://github.com/mhgolkar/Arrow/commit/1f9e838eaa669b5111607a2bbca97d7b23f43468) is now in the main branch to make *Reset on Reinspection* behavior optional. The behavior is by default active (for backward compatibility). It can be disabled from Quick Preferences menu.

Thanks for the valuable feedback

**Comment by diegopau** [comment]
This is great! yes, having the Reset on Reinspection as an option woks well. Thank you for addressing my request so quickly!
